os: osx
language: swift

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

matrix:
  include:
    - osx_image: xcode12

script:
  - swift test
  - xcodebuild test -scheme Sodium_iOS -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest' -sdk iphonesimulator | xcpretty

before_install:
  - brew update
  - brew install libsodium
